name: Deploy App

on:
  workflow_dispatch:
    inputs:
      rollback:
        description: 'Is this a rollback deployment?'
        required: false
        default: 'false'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set rollback input
        run: echo "ROLLBACK=${{ github.event.inputs.rollback }}" >> $GITHUB_ENV

      - name: Simulate Deploy
        run: echo "Deploying..."  # replace with actual deploy

      - name: Save Deployment Metadata
        run: |
          echo '[{
            "deployment_id": "${{ github.run_id }}",
            "repo": "${{ github.repository }}",
            "status": "success",
            "rollback": '${{ env.ROLLBACK }}',
            "timestamp": "${{ github.run_started_at }}"
          }]' > deployment_logs.json
      - name: Append to Deployment History and Push
        env:
          GH_PAT: ${{ secrets.GH_PAT }}  # Add this in your repo secrets
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git clone https://x-access-token:${GH_PAT}@github.com/${{ github.repository }} repo
          cd repo

          mkdir -p .github/data

          DEPLOY_LOG_FILE=".github/data/deployments.json"

          if [ ! -f "$DEPLOY_LOG_FILE" ]; then
            echo "[]" > "$DEPLOY_LOG_FILE"
          fi

          jq --argjson new_entry "$(cat ../deployment_logs.json | jq '.[0]')" \
             '. += [$new_entry]' "$DEPLOY_LOG_FILE" > tmp.json && mv tmp.json "$DEPLOY_LOG_FILE"

          git add "$DEPLOY_LOG_FILE"
          git commit -m "Update deployment log: ${{ github.run_id }}"
          git push origin HEAD:${{ github.ref_name }}
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: deployment-log
          path: deployment_logs.json
  dqr:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Download Deployment Log Artifact
        uses: actions/download-artifact@v4
        with:
          name: deployment-log
          path: .github/scripts

      - name: Run DQR Script
        run: node .github/scripts/calculate-dqr.js     
