name: Deploy App

permissions:
  contents: write   # allow GITHUB_TOKEN to push logs

on:
  workflow_dispatch:
    inputs:
      rollback:
        description: 'Is this a rollback deployment?'
        required: false
        default: 'false'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set rollback input
        run: echo "ROLLBACK=${{ github.event.inputs.rollback }}" >> $GITHUB_ENV

      - name: Simulate Deploy
        run: echo "🚀 Deploying..."  # replace with actual deploy command

      - name: Save Deployment Metadata
        run: |
          echo '[{
            "deployment_id": "${{ github.run_id }}",
            "repo": "${{ github.repository }}",
            "status": "success",
            "rollback": '${{ env.ROLLBACK }}',
            "timestamp": "${{ github.run_started_at }}"
          }]' > deployment_logs.json

      - name: Append to Deployment History and Push
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git clone https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }} repo
          cd repo

          mkdir -p .github/data
          DEPLOY_LOG_FILE=".github/data/deployments.json"

          if [ ! -f "$DEPLOY_LOG_FILE" ]; then
            echo "[]" > "$DEPLOY_LOG_FILE"
          fi

          jq --argjson new_entry "$(cat ../_
